replicaCount: 1

image:
  repository: ghcr.io/felixzmn/docker/website
  pullPolicy: IfNotPresent
  tag: "1.0.0"

imagePullSecrets:
  - name: regcred
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: 
  app.kubernetes.io/component: website


podSecurityContext: {}
  # fsGroup: 2000

securityContext: 
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

  hosts:
    - host: test.example.de
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: website-tls
     hosts:
       - test.example.de

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
